[package]
name = "cpuid"
version = "0.1.0"
authors = ["Daniel Robertson <dan.robertson@anidata.org>"]
build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]

[build-dependencies]
cc = "1.0.4"
